cdiv – fortran-astrodynamics-toolkit
cdiv Subroutine
13 statements
Source File
private subroutine cdiv(Ar, Ai, Br, Bi, Cr, Ci)
Compute the complex quotient of two complex numbers.
Complex division, (CR,CI) = (AR,AI)/(BR,BI)
Revision History
811101 DATE WRITTEN
891214 Prologue converted to Version 4.0 format. (BAB)
900402 Added TYPE section. (WRB)
Arguments
Type Intent Optional Attributes Name
real(kind=wp) :: Ar
real(kind=wp) :: Ai
real(kind=wp) :: Br
real(kind=wp) :: Bi
real(kind=wp) :: Cr
real(kind=wp) :: Ci
Called by
Contents
Source Code
cdiv
Source Code
 subroutine cdiv(Ar, Ai, Br, Bi, Cr, Ci)
    implicit none
    real(wp) :: Ar, Ai, Br, Bi, Cr, Ci
    real(wp) :: s, ars, ais, brs, bis
    s = abs(Br) + abs(Bi)
    ars = Ar/s
    ais = Ai/s
    brs = Br/s
    bis = Bi/s
    s = brs**2 + bis**2
    Cr = (ars*brs + ais*bis)/s
    Ci = (ais*brs - ars*bis)/s
 end subroutine cdiv
Call graph
hqr2 calls cdiv
rg calls hqr2
compute_eigenvalues_and_eigenvectors calls rg
compute_real_eigenvalues_and_normalized_eigenvectors calls compute_eigenvalues_and_eigenvectors
eispack_test calls compute_eigenvalues_and_eigenvectors