compute_eigenvalues_and_eigenvectors – fortran-astrodynamics-toolkit
compute_eigenvalues_and_eigenvectors Subroutine
24 statements
Source File
public subroutine compute_eigenvalues_and_eigenvectors(n, a, w, z, ierr)
Uses
numbers_module
Compute the eigenvalues and, optionally, the eigenvectors of a real general matrix.
See also
See rg for more details. This routine is just a wrapper to that one.
Author
Jacob Williams, 3/25/2018
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
the order of the matrix a
real(kind=wp), intent(in), dimension(n,n) :: a
contains the real general matrix
real(kind=wp), intent(out), dimension(n,2) :: w
real and imaginary parts of the eigenvalues
real(kind=wp), intent(out), dimension(n,n) :: z
real and imaginary parts of the eigenvectors
integer, intent(out) :: ierr
output flag from rg
Calls
Called by
Contents
Source Code
compute_eigenvalues_and_eigenvectors
Source Code
    subroutine compute_eigenvalues_and_eigenvectors(n, a, w, z, ierr)
    use numbers_module
    implicit none
    integer,intent(in)                  :: n    !! the order of the matrix `a`
    real(wp),dimension(n,n),intent(in)  :: a    !! contains the real general matrix
    real(wp),dimension(n,2),intent(out) :: w    !! real and imaginary parts of the eigenvalues
    real(wp),dimension(n,n),intent(out) :: z    !! real and imaginary parts of the eigenvectors
    integer,intent(out)                 :: ierr !! output flag from [[rg]]
    integer,parameter :: matz = 1 !! tells [[rg]] to compute eigenvalues and eigenvectors
    integer                 :: i     !! counter
    real(wp),dimension(n,n) :: a_tmp !! copy of [[a]] matrix
    real(wp),dimension(n)   :: fv1   !! work array for [[rg]]
    integer,dimension(n)    :: iv1   !! work array for [[rg]]
    real(wp),dimension(n)   :: wr    !! real part of the eigenvalues
    real(wp),dimension(n)   :: wi    !! imaginary part of the eigenvalues
    ! temp arrays:
    a_tmp = a
    wr = zero
    wi = zero
    ! call the general routine:
    call rg(n, n, a_tmp, wr, wi, matz, z, iv1, fv1, ierr)
    ! pack outputs:
    do i=1,n
        w(i,1) = wr(i)
        w(i,2) = wi(i)
    end do
    end subroutine compute_eigenvalues_and_eigenvectors
Call graph
compute_eigenvalues_and_eigenvectors calls rg
rg calls balbak, hqr, elmhes, balanc, hqr2, eltran
hqr2 calls cdiv
compute_real_eigenvalues_and_normalized_eigenvectors calls compute_eigenvalues_and_eigenvectors
eispack_test calls compute_eigenvalues_and_eigenvectors