cross – fortran-astrodynamics-toolkit
cross Function
Jacob Williams
7 statements
Source File
public pure function cross(r, v) result(rxv)
Cross product of two 3x1 vectors
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: r
real(kind=wp), intent(in), dimension(3) :: v
Return Value real(kind=wp), dimension(3)
Called by
Source Code
    pure function cross(r,v) result(rxv)
    implicit none
    real(wp),dimension(3),intent(in) :: r
    real(wp),dimension(3),intent(in) :: v
    real(wp),dimension(3)            :: rxv
    rxv = [r(2)*v(3) - v(2)*r(3), &
           r(3)*v(1) - v(3)*r(1), &
           r(1)*v(2) - v(1)*r(2) ]
    end function cross
Call graph
angle_between_vectors calls cross
apparent_position calls cross, axis_angle_rotation
axis_angle_rotation calls cross
box_product calls cross
bplane calls cross, ucross
calculate_bplane_data calls cross
cartesian_to_equinoctial calls cross
compute_vinf_vectors calls cross
distance_from_point_to_line calls cross
from_ijk_to_lvlh_mat calls cross
from_ijk_to_rsw_mat calls cross
from_ijk_to_vuw_mat calls cross
get_c_cdot_two_body_rotating calls cross
rv_to_orbital_elements calls cross
solve_lambert_gooding calls cross
ucross calls cross
from_ijk_to_lvlh calls from_ijk_to_lvlh_mat
from_ijk_to_rsw calls from_ijk_to_rsw_mat
from_ijk_to_vuw calls from_ijk_to_vuw_mat
bplane_test calls bplane, calculate_bplane_data, compute_vinf_vectors
get_c_cdot_two_body_rotating_pulsating calls get_c_cdot_two_body_rotating
get_sun_fraction calls apparent_position
lambert_test calls solve_lambert_gooding, solve_lambert_izzo
modified_equinoctial_test calls cartesian_to_equinoctial
solve_lambert_izzo calls ucross
sphere_of_influence_earth_moon calls angle_between_vectors
vector_test calls axis_angle_rotation
from_lvlh_to_ijk_mat calls from_ijk_to_lvlh
from_rsw_to_ijk_mat calls from_ijk_to_rsw
from_vuw_to_ijk_mat calls from_ijk_to_vuw
relative_motion_test calls from_ijk_to_lvlh, from_ijk_to_rsw
from_lvlh_to_ijk calls from_lvlh_to_ijk_mat
from_rsw_to_ijk calls from_rsw_to_ijk_mat
from_vuw_to_ijk calls from_vuw_to_ijk_mat