cross_matrix – fortran-astrodynamics-toolkit
cross_matrix Function
Jacob Williams
7/20/2014
8 statements
Source File
public pure function cross_matrix(r) result(rcross)
Computes the cross product matrix, where: cross(a,b) == matmul(cross_matrix(a),b)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: r
Return Value real(kind=wp), dimension(3,3)
Called by
Source Code
    pure function cross_matrix(r) result(rcross)
    implicit none
    real(wp),dimension(3),intent(in) :: r
    real(wp),dimension(3,3)          :: rcross
    rcross(:,1) = [zero,r(3),-r(2)]
    rcross(:,2) = [-r(3),zero,r(1)]
    rcross(:,3) = [r(2),-r(1),zero]
    end function cross_matrix
Call graph
axis_angle_rotation_to_rotation_matrix calls cross_matrix
get_c_cdot_two_body_rotating calls cross_matrix
get_c_cdot_two_body_rotating_pulsating calls get_c_cdot_two_body_rotating
vector_test calls axis_angle_rotation_to_rotation_matrix