dcubrt – fortran-astrodynamics-toolkit
dcubrt Function
14 statements
Source File
private pure function dcubrt(x) result(c)
Cube root computed accurately, by incorporating one Newton-Raphson iteration.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x
Return Value real(kind=wp)
Called by
Contents
Source Code
dcubrt
Source Code
    pure function dcubrt(x) result(c)
    implicit none
    real(wp)            :: c
    real(wp),intent(in) :: x
    real(wp) :: y
    if (x==zero) then
        c = zero
    else
        y = abs(x)
        c = y**athird
        c = c - athird*(c - y/c**2)
        c = sign(c,x)
    end if
    end function dcubrt
Call graph
dcbsol calls dcubrt
shkepl calls dcubrt
ekepl calls dcbsol
els2pv calls dcbsol, shkepl, ekepl
els3pv calls els2pv
propagate calls els3pv