ephemeris_test – fortran-astrodynamics-toolkit
ephemeris_test Subroutine
102 statements
Source File
public subroutine ephemeris_test()
Uses
time_module
celestial_body_module
Ephemeris test routine.
Ephemeris files
This routine requires the DE405 and DE421 JPL binary ephemeris files to be present in the ./eph directory. These can be built by using the instructions here.
See also get_third_party.sh script in the repo.
Arguments
None
Calls
Source Code
    subroutine ephemeris_test()
    use time_module, only: jd_to_et
    use celestial_body_module, fat_wp => wp
    implicit none
    ! note: the low-level functions use real64 variables.
    character(len=6),dimension(nmax) :: nams
    real(wp),dimension(6) :: diffrv
    real(wp),dimension(3) :: ss
    real(wp),dimension(nmax) :: vals
    integer :: nvs,ntarg,nctr,i,j
    type(jpl_ephemeris) :: eph405, eph421
    logical :: status_ok_405,status_ok_421
    real(wp) :: jd_64, rv_64(6), rv1_64(6), rv2_64(6)
    real(fat_wp) :: et
    real(fat_wp),dimension(3) :: r
    real(fat_wp),dimension(6) :: rv,rv1,rv2
    real(fat_wp) :: jd
    character(len=*),parameter :: ephemeris_file_405 = './eph/JPLEPH.405' !! JPL DE405 ephemeris file
    character(len=*),parameter :: ephemeris_file_421 = './eph/JPLEPH.421' !! JPL DE421 ephemeris file
    write(*,*) ''
    write(*,*) '---------------'
    write(*,*) ' ephemeris_test'
    write(*,*) '---------------'
    write(*,*) ''
    !initialize:
    call eph405%initialize(filename=ephemeris_file_405,status_ok=status_ok_405)
    call eph421%initialize(filename=ephemeris_file_421,status_ok=status_ok_421)
    if (status_ok_405) then
        !get some constants from the file:
        call eph405%get_constants(nams,vals,ss,nvs)
        write(*,'(A)') ''
        write(*,'(A)') 'Ephemeris initialized'
        write(*,'(A,1X,F15.3,1X,A,1X,F15.3)') 'JD range: ',ss(1), 'to ', ss(2)
        write(*,'(A)') ''
        do i=1,nvs
            write(*,'(A,1X,D25.16)') nams(i), vals(i)
        end do
        jd = 2451536.5_wp   ! julian date
        et = jd_to_et(jd)  ! ephemeris time
        if (jd < ss(1) .or. jd > ss(2)) then
            write(*,'(A)') ''
            write(*,*) 'error: jed out of bounds.'
            write(*,*) 'jed   = ', jd
            write(*,*) 'ss(1) = ', ss(1)
            write(*,*) 'ss(2) = ', ss(2)
        else
            !test DE405:
            do j=1,2
                if (j==1) then
                    ntarg = 3      !earth
                    nctr  = 11     !sun
                else
                    ntarg = 10     !moon
                    nctr  = 3      !earth
                end if
                write(*,*) ''
                write(*,*) 'DE405'
                write(*,*) 'state of "'//trim(list_of_bodies(ntarg))//&
                            '" wrt "'//trim(list_of_bodies(nctr))//'"'
                do i=1,10
                    jd_64 = jd
                    call eph405%get_state( jd_64, ntarg, nctr, rv_64, status_ok_405)
                    rv = rv_64
                    write(*,'(F15.2,1X,*(E25.16,1X))') jd, norm2(rv(1:3)), rv
                    jd = jd + 10.0_wp
                end do
            end do
        end if
    else
        write(*,*) 'Error opening DE405 ephemeris file'
    end if
    if (status_ok_405 .and. status_ok_421) then
        !compare DE405 with DE421
        do j=1,2
            if (j==1) then
                ntarg = 3      !earth
                nctr  = 11     !sun
            else
                ntarg = 10     !moon
                nctr  = 3      !earth
            end if
            write(*,*) ''
            write(*,*) 'DE421 - DE405 Difference'
            write(*,*) 'state of "'//trim(list_of_bodies(ntarg))//&
                        '" wrt "'//trim(list_of_bodies(nctr))//'"'
            do i=1,10
                jd_64 = jd
                call eph405%get_state( jd_64, ntarg, nctr, rv1_64, status_ok_405)
                rv1 = rv1_64
                jd_64 = jd
                call eph421%get_state( jd_64, ntarg, nctr, rv2_64, status_ok_421)
                rv2 = rv2_64
                diffrv = rv2 - rv1
                write(*,'(F15.2,1X,*(E25.16,1X))') jd, norm2(diffrv(1:3)), norm2(diffrv(4:6))
                jd = jd + 10.0_wp
            end do
        end do
        ! compare get_rv with get_r
        call eph405%get_rv(et,body_earth,body_moon,rv,status_ok_405)
        call eph405%get_r(et,body_earth,body_moon,r,status_ok_405)
        write(*,*) ''
        write(*,*) 'r - rv(1:3) = ', r - rv(1:3)
        if (.not. all(r - rv(1:3) == zero)) error stop 'error in ephemeris'
        write(*,*) ''
    else
        write(*,*) 'Error opening DE421 ephemeris file'
    end if
    !cleanup:
    call eph405%close()
    call eph421%close()
    end subroutine ephemeris_test
Call graph
ephemeris_test calls get_constants, get_r_from_jpl_ephemeris, get_rv_from_jpl_ephemeris, get_state, initialize_ephemeris, jd_to_et
get_r_from_jpl_ephemeris calls get_state, et_to_jd, spice_id_to_old_id
get_rv_from_jpl_ephemeris calls get_state, et_to_jd, spice_id_to_old_id
get_state calls state
state calls interp, split