et_to_jd – fortran-astrodynamics-toolkit
et_to_jd Function
Jacob Williams
2/3/2015
7 statements
Source File
public pure function et_to_jd(et) result(jd)
Uses
conversion_module
Convert ephemeris time (seconds from J2000 epoch) to Julian date.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: et
ephemeris time [sec from J2000 epoch]
Return Value real(kind=wp)
Julian date [days]
Called by
Contents
Source Code
et_to_jd
Source Code
    pure function et_to_jd(et) result(jd)
    use conversion_module, only: sec2day
    implicit none
    real(wp),intent(in) :: et   !! ephemeris time [sec from J2000 epoch]
    real(wp)            :: jd   !! Julian date [days]
    jd = jd_j2000 + et*sec2day
    end function et_to_jd
Call graph
standish_rv_func calls et_to_jd
get_rv_from_jpl_ephemeris calls et_to_jd
standish_module_test calls et_to_jd