fill_char_vector_with_vector – fortran-astrodynamics-toolkit
fill_char_vector_with_vector Subroutine
10 statements
Source File
private subroutine fill_char_vector_with_vector(x, vals, i)
Put the vector in the vector and update the index (character version)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout), dimension(:) :: x
character(len=*), intent(in), dimension(:) :: vals
integer, intent(inout) :: i
should be initialized to 0 before the first call
Calls
Called by
Contents
Source Code
fill_char_vector_with_vector
Source Code
    subroutine fill_char_vector_with_vector(x, vals, i)
    implicit none
    character(len=*),dimension(:),intent(inout) :: x
    character(len=*),dimension(:),intent(in) :: vals
    integer,intent(inout) :: i !! should be initialized to 0 before the first call
    integer :: j !! counter
    do j = 1, size(vals)
        call fill_vector(x,vals(j),i)
    end do
    end subroutine fill_char_vector_with_vector
Call graph
fill_char_vector_with_vector calls fill_vector
fill_vector calls fill_char_vector_with_vector, fill_vector_with_vector, fill_char_vector_with_scalar, fill_vector_with_scalar
fill_vector_with_vector calls fill_vector