FL – fortran-astrodynamics-toolkit
FL Function
Jacob Williams
9/20/2014
11 statements
Source File
private function FL(n)
The FL factorial function from [1].
References
W. M. Lear, "The Programs TRAJ1 and TRAJ2", JSC Mission Planning and Analysis Division, JSC-22512, 87-FM-4, April 1987
Note
Coded from [1] with some modifications.
SOURCE
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
Return Value real(kind=wp)
Called by
Source Code
    function FL(n)
    implicit none
    real(wp) :: FL
    integer,intent(in) :: n
    integer :: i
    FL = one
    if (n==0 .or. n==1) return
    do i=2,n
        FL = FL*i
    end do
    end function FL
Call graph
convert calls fl
read_geopotential_file calls fl, convert
geopotential_module_test calls read_geopotential_file