from_ijk_to_vuw_rv – fortran-astrodynamics-toolkit
from_ijk_to_vuw_rv Subroutine
11 statements
Source File
private subroutine from_ijk_to_vuw_rv(mu, rt_ijk, vt_ijk, r_ijk, v_ijk, dr_vuw, dv_vuw)
Transform a position (and optionally velocity) vector from IJK to VUW.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: mu
gravitational parameter [km^3/s^2]
real(kind=wp), intent(in), dimension(3) :: rt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: vt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: r_ijk
Chaser IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: v_ijk
Chaser IJK absolute position vector [km]
real(kind=wp), intent(out), dimension(3) :: dr_vuw
Chaser vuw position vector relative to target [km]
real(kind=wp), intent(out), optional, dimension(3) :: dv_vuw
Chaser vuw position vector relative to target [km]
Calls
Called by
Source Code
    subroutine from_ijk_to_vuw_rv(mu,rt_ijk,vt_ijk,r_ijk,v_ijk,dr_vuw,dv_vuw)
    implicit none
    real(wp),intent(in)                        :: mu       !! gravitational parameter [km^3/s^2]
    real(wp),dimension(3),intent(in)           :: rt_ijk   !! Target IJK absolute position vector [km]
    real(wp),dimension(3),intent(in)           :: vt_ijk   !! Target IJK absolute position vector [km]
    real(wp),dimension(3),intent(in)           :: r_ijk    !! Chaser IJK absolute position vector [km]
    real(wp),dimension(3),intent(in)           :: v_ijk    !! Chaser IJK absolute position vector [km]
    real(wp),dimension(3),intent(out)          :: dr_vuw  !! Chaser vuw position vector relative to target [km]
    real(wp),dimension(3),intent(out),optional :: dv_vuw  !! Chaser vuw position vector relative to target [km]
    call from_ijk_to_frame_rv(mu,from_ijk_to_vuw_mat,rt_ijk,vt_ijk,r_ijk,v_ijk,dr_vuw,dv_vuw)
    end subroutine from_ijk_to_vuw_rv
Call graph
from_ijk_to_vuw_rv calls from_ijk_to_frame_rv
from_ijk_to_vuw calls from_ijk_to_vuw_rv
from_vuw_to_ijk_mat calls from_ijk_to_vuw
from_vuw_to_ijk calls from_vuw_to_ijk_mat