from_ijk_to_lvlh_rv – fortran-astrodynamics-toolkit
from_ijk_to_lvlh_rv Subroutine
Jacob Williams
8/23/2014
22 statements
Source File
private subroutine from_ijk_to_lvlh_rv(rt_ijk, vt_ijk, r_ijk, v_ijk, dr_lvlh, dv_lvlh)
Transform a position (and optionally velocity) vector from IJK to LVLH.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: rt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: vt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: r_ijk
Chaser IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: v_ijk
Chaser IJK absolute position vector [km]
real(kind=wp), intent(out), dimension(3) :: dr_lvlh
Chaser LVLH position vector relative to target [km]
real(kind=wp), intent(out), optional, dimension(3) :: dv_lvlh
Chaser LVLH position vector relative to target [km]
Calls
Called by
Source Code
    subroutine from_ijk_to_lvlh_rv(rt_ijk,vt_ijk,r_ijk,v_ijk,dr_lvlh,dv_lvlh)
    implicit none
    real(wp),dimension(3),intent(in)           :: rt_ijk  !! Target IJK absolute position vector [km]
    real(wp),dimension(3),intent(in)           :: vt_ijk  !! Target IJK absolute position vector [km]
    real(wp),dimension(3),intent(in)           :: r_ijk   !! Chaser IJK absolute position vector [km]
    real(wp),dimension(3),intent(in)           :: v_ijk   !! Chaser IJK absolute position vector [km]
    real(wp),dimension(3),intent(out)          :: dr_lvlh !! Chaser LVLH position vector relative to target [km]
    real(wp),dimension(3),intent(out),optional :: dv_lvlh !! Chaser LVLH position vector relative to target [km]
    real(wp),dimension(3,3) :: c
    real(wp),dimension(3,3) :: cdot
    real(wp),dimension(3) :: dr_ijk, dv_ijk
    !IJK state of chaser relative to target:
    dr_ijk = r_ijk - rt_ijk    ! [target + delta = chaser]
    if (present(dv_lvlh)) then
        dv_ijk = v_ijk - vt_ijk ! [target + delta = chaser]
        call from_ijk_to_lvlh(rt_ijk,vt_ijk,c=c,cdot=cdot)
        dr_lvlh = matmul( c, dr_ijk )
        dv_lvlh = matmul( cdot, dr_ijk ) + matmul( c, dv_ijk )
    else
        call from_ijk_to_lvlh(r_ijk,v_ijk,c=c)
        dr_lvlh = matmul( c, dr_ijk )
    end if
    end subroutine from_ijk_to_lvlh_rv
Call graph
from_ijk_to_lvlh_rv calls from_ijk_to_lvlh
from_ijk_to_lvlh calls from_ijk_to_lvlh_rv, from_ijk_to_lvlh_mat
from_ijk_to_lvlh_mat calls cross, uhat_dot, unit
from_lvlh_to_ijk_mat calls from_ijk_to_lvlh
relative_motion_test calls from_ijk_to_lvlh
from_lvlh_to_ijk calls from_lvlh_to_ijk_mat, from_lvlh_to_ijk_rv
from_lvlh_to_ijk_rv calls from_lvlh_to_ijk