from_ijk_to_rsw_rv – fortran-astrodynamics-toolkit
from_ijk_to_rsw_rv Subroutine
Jacob Williams
8/23/2014
22 statements
Source File
private subroutine from_ijk_to_rsw_rv(rt_ijk, vt_ijk, r_ijk, v_ijk, dr_rsw, dv_rsw)
Transform a position (and optionally velocity) vector from IJK to RSW.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: rt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: vt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: r_ijk
Chaser IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: v_ijk
Chaser IJK absolute position vector [km]
real(kind=wp), intent(out), dimension(3) :: dr_rsw
Chaser RSW position vector relative to target [km]
real(kind=wp), intent(out), optional, dimension(3) :: dv_rsw
Chaser RSW position vector relative to target [km]
Calls
Called by
Source Code
    subroutine from_ijk_to_rsw_rv(rt_ijk,vt_ijk,r_ijk,v_ijk,dr_rsw,dv_rsw)
    implicit none
    real(wp),dimension(3),intent(in)           :: rt_ijk   !! Target IJK absolute position vector [km]
    real(wp),dimension(3),intent(in)           :: vt_ijk   !! Target IJK absolute position vector [km]
    real(wp),dimension(3),intent(in)           :: r_ijk    !! Chaser IJK absolute position vector [km]
    real(wp),dimension(3),intent(in)           :: v_ijk    !! Chaser IJK absolute position vector [km]
    real(wp),dimension(3),intent(out)          :: dr_rsw   !! Chaser RSW position vector relative to target [km]
    real(wp),dimension(3),intent(out),optional :: dv_rsw   !! Chaser RSW position vector relative to target [km]
    real(wp),dimension(3,3) :: c
    real(wp),dimension(3,3) :: cdot
    real(wp),dimension(3) :: dr_ijk, dv_ijk
    dr_ijk = r_ijk - rt_ijk  ! delta = chaser - target
    if (present(dv_rsw)) then
        dv_ijk = v_ijk - vt_ijk  ! delta = chaser - target
        call from_ijk_to_rsw(rt_ijk,vt_ijk,c=c,cdot=cdot)
        dr_rsw = matmul( c, dr_ijk )
        dv_rsw = matmul( cdot, dr_ijk ) + matmul( c, dv_ijk )
    else
        call from_ijk_to_rsw(rt_ijk,vt_ijk,c=c)
        dr_rsw = matmul( c, dr_ijk )
    end if
    end subroutine from_ijk_to_rsw_rv
Call graph
from_ijk_to_rsw_rv calls from_ijk_to_rsw
from_ijk_to_rsw calls from_ijk_to_rsw_rv, from_ijk_to_rsw_mat
from_ijk_to_rsw_mat calls cross, uhat_dot, unit
from_rsw_to_ijk_mat calls from_ijk_to_rsw
relative_motion_test calls from_ijk_to_rsw
from_rsw_to_ijk calls from_rsw_to_ijk_mat, from_rsw_to_ijk_rv
from_rsw_to_ijk_rv calls from_rsw_to_ijk