from_rsw_to_ijk_rv – fortran-astrodynamics-toolkit
from_rsw_to_ijk_rv Subroutine
Jacob Williams
8/23/2014
19 statements
Source File
private subroutine from_rsw_to_ijk_rv(rt_ijk, vt_ijk, dr_rsw, dv_rsw, r_ijk, v_ijk)
Transform a position (and optionally velocity) vector from RSW to IJK.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: rt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: vt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: dr_rsw
Chaser RSW position vector [km]
real(kind=wp), intent(in), dimension(3) :: dv_rsw
Chaser RSW velocity vector [km/s]
real(kind=wp), intent(out), dimension(3) :: r_ijk
Chaser IJK absolute position vector [km]
real(kind=wp), intent(out), optional dimension(3) :: v_ijk
Chaser IJK absolute velocity vector [km/s]
Calls
Called by
Contents
Source Code
from_rsw_to_ijk_rv
Source Code
    subroutine from_rsw_to_ijk_rv(rt_ijk,vt_ijk,dr_rsw,dv_rsw,r_ijk,v_ijk)
    implicit none
    real(wp),dimension(3),intent(in)            :: rt_ijk   !! Target IJK absolute position vector [km]
    real(wp),dimension(3),intent(in)            :: vt_ijk   !! Target IJK absolute position vector [km]
    real(wp),dimension(3),intent(in)            :: dr_rsw   !! Chaser RSW position vector [km]
    real(wp),dimension(3),intent(in)            :: dv_rsw   !! Chaser RSW velocity vector [km/s]
    real(wp),dimension(3),intent(out)           :: r_ijk    !! Chaser IJK absolute position vector [km]
    real(wp),dimension(3),intent(out),optional  :: v_ijk    !! Chaser IJK absolute velocity vector [km/s]
    real(wp),dimension(3,3) :: c
    real(wp),dimension(3,3) :: cdot
    if (present(v_ijk)) then
        call from_rsw_to_ijk(rt_ijk,vt_ijk,c=c,cdot=cdot)
        r_ijk = rt_ijk + matmul( c, dr_rsw )
        v_ijk = vt_ijk + matmul( cdot, dr_rsw ) + matmul( c, dv_rsw )
    else
        call from_rsw_to_ijk(rt_ijk,vt_ijk,c=c)
        r_ijk = rt_ijk + matmul( c, dr_rsw )
    end if
    end subroutine from_rsw_to_ijk_rv
Call graph
from_rsw_to_ijk_rv calls from_rsw_to_ijk
from_rsw_to_ijk calls from_rsw_to_ijk_rv, from_rsw_to_ijk_mat
from_rsw_to_ijk_mat calls from_ijk_to_rsw
from_ijk_to_rsw calls from_ijk_to_rsw_mat, from_ijk_to_rsw_rv
from_ijk_to_rsw_mat calls cross, unit, uhat_dot
from_ijk_to_rsw_rv calls from_ijk_to_rsw