from_lvlh_to_ijk_rv – fortran-astrodynamics-toolkit
from_lvlh_to_ijk_rv Subroutine
Jacob Williams
8/23/2014
19 statements
Source File
private subroutine from_lvlh_to_ijk_rv(rt_ijk, vt_ijk, dr_lvlh, dv_lvlh, r_ijk, v_ijk)
Transform a position (and optionally velocity) vector from LVLH to IJK.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: rt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: vt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: dr_lvlh
Chaser LVLH position vector relative to target [km]
real(kind=wp), intent(in), dimension(3) :: dv_lvlh
Chaser LVLH position vector relative to target [km]
real(kind=wp), intent(out), dimension(3) :: r_ijk
Chaser IJK absolute position vector [km]
real(kind=wp), intent(out), optional dimension(3) :: v_ijk
Chaser IJK absolute position vector [km]
Calls
Called by
Contents
Source Code
from_lvlh_to_ijk_rv
Source Code
    subroutine from_lvlh_to_ijk_rv(rt_ijk,vt_ijk,dr_lvlh,dv_lvlh,r_ijk,v_ijk)
    implicit none
    real(wp),dimension(3),intent(in)            :: rt_ijk   !! Target IJK absolute position vector [km]
    real(wp),dimension(3),intent(in)            :: vt_ijk   !! Target IJK absolute position vector [km]
    real(wp),dimension(3),intent(in)            :: dr_lvlh  !! Chaser LVLH position vector relative to target [km]
    real(wp),dimension(3),intent(in)            :: dv_lvlh  !! Chaser LVLH position vector relative to target [km]
    real(wp),dimension(3),intent(out)           :: r_ijk    !! Chaser IJK absolute position vector [km]
    real(wp),dimension(3),intent(out),optional  :: v_ijk    !! Chaser IJK absolute position vector [km]
    real(wp),dimension(3,3) :: c
    real(wp),dimension(3,3) :: cdot
    if (present(v_ijk)) then
        call from_lvlh_to_ijk(rt_ijk,vt_ijk,c=c,cdot=cdot)
        !chaser = target + delta:
        r_ijk = rt_ijk + matmul( c, dr_lvlh )
        v_ijk = vt_ijk + matmul( cdot, dr_lvlh ) + matmul( c, dv_lvlh )
    else
        call from_lvlh_to_ijk(rt_ijk,vt_ijk,c=c)
        r_ijk = rt_ijk + matmul( c, dr_lvlh )
    end if
    end subroutine from_lvlh_to_ijk_rv
Call graph
from_lvlh_to_ijk_rv calls from_lvlh_to_ijk
from_lvlh_to_ijk calls from_lvlh_to_ijk_rv, from_lvlh_to_ijk_mat
from_lvlh_to_ijk_mat calls from_ijk_to_lvlh
from_ijk_to_lvlh calls from_ijk_to_lvlh_mat, from_ijk_to_lvlh_rv
from_ijk_to_lvlh_mat calls uhat_dot, unit, cross
from_ijk_to_lvlh_rv calls from_ijk_to_lvlh