from_ijk_to_lvlh_mat – fortran-astrodynamics-toolkit
from_ijk_to_lvlh_mat Subroutine
Jacob Williams
4/19/2014
35 statements
Source File
private subroutine from_ijk_to_lvlh_mat(r, v, a, c, cdot)
Uses
vector_module
Compute the transformation matrices to convert IJK to LVLH.
See also
LVLH Transformations
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: r
position vector of target [km]
real(kind=wp), intent(in), dimension(3) :: v
velocity vector of target [km/s]
real(kind=wp), intent(in), optional dimension(3) :: a
acceleration vector of target [km/s^2] (if not present, then a torque-free force model is assumed)
real(kind=wp), intent(out), dimension(3,3) :: c
C transformation matrix
real(kind=wp), intent(out), optional dimension(3,3) :: cdot
CDOT transformation matrix
Calls
Called by
Contents
Source Code
from_ijk_to_lvlh_mat
Source Code
    subroutine from_ijk_to_lvlh_mat(r,v,a,c,cdot)
    use vector_module, only: unit, cross, uhat_dot
    implicit none
    real(wp),dimension(3),intent(in)             :: r      !! position vector of target [km]
    real(wp),dimension(3),intent(in)             :: v      !! velocity vector of target [km/s]
    real(wp),dimension(3),intent(in),optional    :: a      !! acceleration vector of target [km/s^2]
                                                           !! (if not present, then a torque-free force model is assumed)
    real(wp),dimension(3,3),intent(out)          :: c      !! C transformation matrix
    real(wp),dimension(3,3),intent(out),optional :: cdot   !! CDOT transformation matrix
    real(wp),dimension(3) :: ex_hat,ex_hat_dot
    real(wp),dimension(3) :: ey_hat,ey_hat_dot
    real(wp),dimension(3) :: ez_hat,ez_hat_dot
    real(wp),dimension(3) :: h,h_hat,h_dot
    h      = cross(r,v)
    h_hat  = unit(h)
    ez_hat = -unit(r)
    ey_hat = -h_hat
    ex_hat = cross(ey_hat,ez_hat)
    c(1,:) = ex_hat
    c(2,:) = ey_hat
    c(3,:) = ez_hat
    if (present(cdot)) then
        ez_hat_dot = -uhat_dot(r,v)
        if (present(a)) then
            h_dot      = cross(r,a)
            ey_hat_dot = -uhat_dot(h, h_dot)
            ex_hat_dot = cross(ey_hat_dot,ez_hat) + cross(ey_hat,ez_hat_dot)
        else !assume no external torque
            ey_hat_dot = zero
            ex_hat_dot = cross(ey_hat,ez_hat_dot)
        end if
        cdot(1,:) = ex_hat_dot
        cdot(2,:) = ey_hat_dot
        cdot(3,:) = ez_hat_dot
    end if
    end subroutine from_ijk_to_lvlh_mat
Call graph
from_ijk_to_lvlh_mat calls cross, unit, uhat_dot
from_ijk_to_lvlh calls from_ijk_to_lvlh_mat, from_ijk_to_lvlh_rv
from_ijk_to_lvlh_rv calls from_ijk_to_lvlh
from_lvlh_to_ijk_mat calls from_ijk_to_lvlh
relative_motion_test calls from_ijk_to_lvlh
from_lvlh_to_ijk calls from_lvlh_to_ijk_mat, from_lvlh_to_ijk_rv
from_lvlh_to_ijk_rv calls from_lvlh_to_ijk