get_c_cdot_ecliptic – fortran-astrodynamics-toolkit
get_c_cdot_ecliptic Subroutine
17 statements
Source File
private subroutine get_c_cdot_ecliptic(me, eph, to_icrf, c, cdot, status_ok)
Uses
obliquity_module
rotation matrix for ICRF <-> Mean Ecliptic
Type Bound
ecliptic_frame
Arguments
Type Intent Optional Attributes Name
class(ecliptic_frame), intent(inout) :: me
class(ephemeris_class), intent(inout) :: eph
logical, intent(in) :: to_icrf
real(kind=wp), intent(out), dimension(3,3) :: c
real(kind=wp), intent(out), optional, dimension(3,3) :: cdot
logical, intent(out) :: status_ok
Calls
Called by
Source Code
    subroutine get_c_cdot_ecliptic(me,eph,to_icrf,c,cdot,status_ok)
    !! rotation matrix for ICRF <-> Mean Ecliptic
    use obliquity_module
    implicit none
    class(ecliptic_frame),intent(inout)          :: me
    class(ephemeris_class),intent(inout)         :: eph
    logical,intent(in)                           :: to_icrf
    real(wp),dimension(3,3),intent(out)          :: c
    real(wp),dimension(3,3),intent(out),optional :: cdot
    logical,intent(out)                          :: status_ok
    if (to_icrf) then
        c = mean_ecliptic_to_equatorial_rotmat()
    else
        c = equatorial_to_mean_ecliptic_rotmat()
    end if
    if (present(cdot)) cdot = zero
    status_ok = .true.
    end subroutine get_c_cdot_ecliptic
Call graph
get_c_cdot_ecliptic calls equatorial_to_mean_ecliptic_rotmat, mean_ecliptic_to_equatorial_rotmat
equatorial_to_mean_ecliptic_rotmat calls mean_ecliptic_to_equatorial_rotmat
mean_ecliptic_to_equatorial_rotmat calls mean_obliquity_of_ecliptic_iau1980
transformation_module_test calls get_c_cdot_ecliptic