get_c_cdot_iau_earth – fortran-astrodynamics-toolkit
get_c_cdot_iau_earth Subroutine
12 statements
Source File
private subroutine get_c_cdot_iau_earth(me, eph, to_icrf, c, cdot, status_ok)
rotation matrix for IAU_EARTH <-> ICRF
Type Bound
iau_earth_rotating_frame
Arguments
Type Intent Optional Attributes Name
class(iau_earth_rotating_frame), intent(inout) :: me
class(ephemeris_class), intent(inout) :: eph
for ephemeris computations (assumed to have already been initialized)
logical, intent(in) :: to_icrf
real(kind=wp), intent(out), dimension(3,3) :: c
real(kind=wp), intent(out), optional, dimension(3,3) :: cdot
logical, intent(out) :: status_ok
Calls
Source Code
    subroutine get_c_cdot_iau_earth(me,eph,to_icrf,c,cdot,status_ok)
    !! rotation matrix for IAU_EARTH <-> ICRF
    implicit none
    class(iau_earth_rotating_frame),intent(inout) :: me
    class(ephemeris_class),intent(inout)          :: eph     !! for ephemeris computations (assumed to have already been initialized)
    logical,intent(in)                            :: to_icrf
    real(wp),dimension(3,3),intent(out)           :: c
    real(wp),dimension(3,3),intent(out),optional  :: cdot
    logical,intent(out)                           :: status_ok
    c = icrf_to_iau_earth(me%et)
    !... don't have the cdot code yet... need to refactor iau code ...
    ! see also: ftp://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/spicelib/tisbod.html
    !if (present(cdot)) cdot =
    error stop 'not yet supported'
    status_ok = .true.
    end subroutine get_c_cdot_iau_earth
Call graph
get_c_cdot_iau_earth calls icrf_to_iau_earth
icrf_to_iau_earth calls iau_rotation_matrix
iau_rotation_matrix calls rotation_matrix