get_c_cdot_iau_moon – fortran-astrodynamics-toolkit
get_c_cdot_iau_moon Subroutine
12 statements
Source File
private subroutine get_c_cdot_iau_moon(me, eph, to_icrf, c, cdot, status_ok)
rotation matrix for IAU_MOON <-> ICRF
Arguments
Type Intent Optional Attributes Name
class(iau_moon_rotating_frame), intent(inout) :: me
class(ephemeris_class), intent(inout) :: eph
for ephemeris computations (assumed to have already been initialized)
logical, intent(in) :: to_icrf
real(kind=wp), intent(out), dimension(3,3) :: c
real(kind=wp), intent(out), optional dimension(3,3) :: cdot
logical, intent(out) :: status_ok
Calls
Contents
None
Call graph
get_c_cdot_iau_moon calls icrf_to_iau_moon
icrf_to_iau_moon calls iau_rotation_matrix
iau_rotation_matrix calls rotation_matrix