helio – fortran-astrodynamics-toolkit
helio Subroutine
17 statements
Source File
private pure subroutine helio(np, jd, p, itbl)
For planet np and julian date jd and using using table itbl, return j2000 ecliptic position (au) and velocity (au/yr). in cartesian coordinates (p(1)-p(6)).
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: np
planet 1-9
real(kind=wp), intent(in) :: jd
julian date
real(kind=wp), intent(out), dimension(6) :: p
position (au)/velocity (au/yr)
integer, intent(out) :: itbl
table used or error if zero
Calls
Called by
Source Code
    pure subroutine helio (np, jd, p, itbl)
    implicit none
    integer, intent (in) :: np      !! planet 1-9
    real(wp), intent (in) :: jd     !! julian date
    real(wp), dimension(6), intent(out) :: p !! position (au)/velocity (au/yr)
    integer, intent (out) :: itbl   !! table used or error if zero
    real(wp),dimension(8) :: z  !! elements [a, e, i, l, w, o, ma, ea]
    real(wp),dimension(8) :: po
    z = zero
    po = zero
    itbl = tbl (jd)
    if (itbl > 0) then
        call calcelements (np, jd, itbl, z)
        call el2op (z, po)
        call op2ec (z, po, p)
    end if
    end subroutine helio
Call graph
helio calls calcelements, el2op, op2ec, tbl
calcelements calls kepler
standish_module_test calls helio, standish_rv_func
standish_rv_func calls helio
standish_r_func calls standish_rv_func