icrf_to_iau_earth – fortran-astrodynamics-toolkit
icrf_to_iau_earth Function
Jacob Williams
2/3/2015
12 statements
Source File
public pure function icrf_to_iau_earth(et) result(rotmat)
Rotation matrix from ICRF to IAU_EARTH.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: et
ephemeris time [sec]
Return Value real(kind=wp),dimension(3,3)
the rotation matrix
Calls
Called by
Contents
Source Code
icrf_to_iau_earth
Source Code
    pure function icrf_to_iau_earth(et) result(rotmat)
    implicit none
    real(wp),intent(in)     :: et        !! ephemeris time [sec]
    real(wp),dimension(3,3) :: rotmat    !! the rotation matrix
    real(wp) :: w,dec,ra,d,t
    d = et * sec2day     !interval in days from the J2000 epoch
    t = et * sec2century !interval in Julian centuries (36525 days) from the J2000 epoch
    ra  = (         - 0.641_wp * t          ) * deg2rad
    dec = ( 90.0_wp - 0.557_wp * t          ) * deg2rad
    w   = ( 190.147_wp + 360.9856235_wp * d ) * deg2rad
    rotmat = iau_rotation_matrix(w,dec,ra)
    end function icrf_to_iau_earth
Call graph
icrf_to_iau_earth calls iau_rotation_matrix
iau_rotation_matrix calls rotation_matrix
iau_test calls icrf_to_iau_earth
get_c_cdot_iau_earth calls icrf_to_iau_earth