julian_date_intsec – fortran-astrodynamics-toolkit
julian_date_intsec Function
Jacob Williams
1/21/2015
11 statements
Source File
private pure function julian_date_intsec(y, m, d, hour, minute, second) result(julian_date)
Returns the Julian date for the specified YEAR, MONTH, DAY, HR, MIN, SEC.
Valid for any Gregorian calendar date producing a Julian date greater than zero.
History
JW : 10/4/2017 : moved main code to julian_date_realsec routine.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: y
integer, intent(in) :: m
integer, intent(in) :: d
integer, intent(in) :: hour
integer, intent(in) :: minute
integer, intent(in) :: second
Return Value real(kind=wp)
Calls
Called by
Source Code
    pure function julian_date_intsec(y,m,d,hour,minute,second) result(julian_date)
    implicit none
    real(wp)           :: julian_date
    integer,intent(in) :: y
    integer,intent(in) :: m
    integer,intent(in) :: d
    integer,intent(in) :: hour
    integer,intent(in) :: minute
    integer,intent(in) :: second
    ! call the other routine:
    julian_date = julian_date_realsec(y,m,d,hour,minute,real(second,wp))
    end function julian_date_intsec
Call graph
julian_date_intsec calls julian_date_realsec
julian_date_realsec calls julian_day
julian_date calls julian_date_intsec
time_module_test calls julian_date