julian_day – fortran-astrodynamics-toolkit
julian_day Function
Jacob Williams
7 statements
Source File
public pure function julian_day(y, m, d)
Returns the Julian day number (i.e., the Julian date at Greenwich noon) on the specified YEAR, MONTH, and DAY.
Valid for any Gregorian calendar date producing a Julian date greater than zero.
Reference
USNO
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: y
year (YYYY)
integer, intent(in) :: m
month (MM)
integer, intent(in) :: d
day (DD)
Return Value integer
Called by
Source Code
    pure integer function julian_day(y,m,d)
    implicit none
    integer,intent(in) :: y   !! year (YYYY)
    integer,intent(in) :: m   !! month (MM)
    integer,intent(in) :: d   !! day (DD)
    julian_day = d-32075+1461*(y+4800+(m-14)/12)/4+367*&
                 (m-2-(m-14)/12*12)/12-3*((y+4900+(m-14)/12)/100)/4
    end function julian_day
Call graph
julian_date_realsec calls julian_day
julian_date calls julian_date_realsec, julian_date_intsec
julian_date_intsec calls julian_date_realsec
time_module_test calls julian_date