julian_date_realsec – fortran-astrodynamics-toolkit
julian_date_realsec Function
Jacob Williams
1/21/2015
13 statements
Source File
private pure function julian_date_realsec(y, m, d, hour, minute, second) result(julian_date)
Returns the Julian date for the specified YEAR, MONTH, DAY, HR, MIN, SEC.
Valid for any Gregorian calendar date producing a Julian date greater than zero.
History
JW : 10/4/2017 : made second a real value & renamed routine.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: y
integer, intent(in) :: m
integer, intent(in) :: d
integer, intent(in) :: hour
integer, intent(in) :: minute
real(kind=wp), intent(in) :: second
Return Value real(kind=wp)
Calls
Called by
Contents
Source Code
julian_date_realsec
Source Code
    pure function julian_date_realsec(y,m,d,hour,minute,second) result(julian_date)
    implicit none
    real(wp)            :: julian_date
    integer,intent(in)  :: y
    integer,intent(in)  :: m
    integer,intent(in)  :: d
    integer,intent(in)  :: hour
    integer,intent(in)  :: minute
    real(wp),intent(in) :: second
    integer :: julian_day_number
    julian_day_number = julian_day(y,m,d)
    julian_date = real(julian_day_number,wp) + &
                    (hour-12.0_wp)/24.0_wp + &
                    minute/1440.0_wp + &
                    second/86400.0_wp
    end function julian_date_realsec
Call graph
julian_date_realsec calls julian_day
julian_date_intsec calls julian_date_realsec
julian_date calls julian_date_realsec, julian_date_intsec
time_module_test calls julian_date