mean_obliquity_of_ecliptic_iau1980 – fortran-astrodynamics-toolkit
mean_obliquity_of_ecliptic_iau1980 Function
9 statements
Source File
public pure function mean_obliquity_of_ecliptic_iau1980(et) result(e)
Mean obliquity of the ecliptic, IAU 1980 formula.
Note
This equation is consistent with the one from the SPICE zzmobliq routine.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: et
ephemeris time (sec)
Return Value real(kind=wp)
obliquity of ecliptic (deg)
Called by
Source Code
    pure function mean_obliquity_of_ecliptic_iau1980(et) result(e)
    implicit none
    real(wp),intent(in) :: et  !! ephemeris time (sec)
    real(wp)            :: e   !! obliquity of ecliptic (deg)
    real(wp) :: t  !! time in centuries from the J2000 epoch
    real(wp),dimension(0:3),parameter :: c = [84381.448_wp,&
                                              -46.8150_wp,&
                                              -0.00059_wp,&
                                              +0.001813_wp] !! coefficients
    ! convert input time to centuries:
    t = et*sec2day*day2century
    ! use horner's rule:
    e = (c(0)+t*(c(1)+t*(c(2)+t*c(3))))*arcsec2deg
    end function mean_obliquity_of_ecliptic_iau1980
Call graph
mean_ecliptic_to_equatorial_rotmat calls mean_obliquity_of_ecliptic_iau1980
equatorial_to_mean_ecliptic_rotmat calls mean_ecliptic_to_equatorial_rotmat
get_c_cdot_ecliptic calls mean_ecliptic_to_equatorial_rotmat, equatorial_to_mean_ecliptic_rotmat
transformation_module_test calls get_c_cdot_ecliptic