number_of_coefficients – fortran-astrodynamics-toolkit
number_of_coefficients Function
Jacob Williams
9/20/2014
12 statements
Source File
private pure function number_of_coefficients(n, m) result(np)
Number of (c,s) coefficients for n x m geopotential model Starting with n=2,m=0.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
degree
integer, intent(in) :: m
order
Return Value integer
number of coefficients
Called by
Source Code
    pure function number_of_coefficients(n,m) result(np)
    implicit none
    integer            :: np  !! number of coefficients
    integer,intent(in) :: n   !! degree
    integer,intent(in) :: m   !! order
    integer :: i  !counter
    if (n>=m .and. n>1) then
        np = m - 1 + sum( [ (i, i=n,2,-1) ] )
    else
        np = -999    !error
    end if
    end function number_of_coefficients
Call graph
geopotential_module_test calls number_of_coefficients, read_geopotential_file
read_geopotential_file calls number_of_coefficients