philambda_quadrant – fortran-astrodynamics-toolkit
philambda_quadrant Subroutine
20 statements
Source File
private subroutine philambda_quadrant(x, y, z, phi, lambda)
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x
real(kind=wp), intent(in) :: y
real(kind=wp), intent(in) :: z
real(kind=wp), intent(inout) :: phi
real(kind=wp), intent(inout) :: lambda
Called by
Source Code
subroutine philambda_quadrant(x, y, z, phi, lambda)
    real(wp),intent(in) :: x, y, z
    real(wp),intent(inout) :: phi, lambda
    if (z < zero) then
        phi = -phi
    end if
    if (x >= zero) then
        if (y >= zero) then
            lambda = lambda
        else
            lambda = -lambda
        end if
    else
        if (y >= zero) then
            lambda = pi-lambda
        else
            lambda = lambda-pi
        end if
    end if
end subroutine philambda_quadrant
Call graph
cartesian_to_geodetic_triaxial calls philambda_quadrant
cartesianintogeodetici calls philambda_quadrant
cartesianintogeodeticii calls philambda_quadrant