return_a_string – fortran-astrodynamics-toolkit
return_a_string Subroutine
6 statements
Source File
private subroutine return_a_string(ival, buffer) bind(c,name='return_a_string')
Just a test of f_string_to_c_ptr.
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in), value :: ival
type(c_ptr), intent(inout) :: buffer
a preallocated string buffer
Calls
Source Code
    subroutine return_a_string(ival,buffer) bind(c,name='return_a_string')
    implicit none
    integer(c_int),intent(in),value :: ival
    type(c_ptr),intent(inout)       :: buffer  !! a preallocated string buffer
    call f_string_to_c_ptr(repeat('*',ival),buffer)
    end subroutine return_a_string
Call graph
return_a_string calls f_string_to_c_ptr
f_string_to_c_ptr calls strlen, s