set_function – fortran-astrodynamics-toolkit
set_function Subroutine
Jacob Williams
7/19/2014
6 statements
Source File
private subroutine set_function(me, f)
Set the function to be minimized.
Type Bound
brent_class
Arguments
Type Intent Optional Attributes Name
class(brent_class), intent(inout) :: me
procedure(func) :: f
Called by
Source Code
    subroutine set_function(me,f)
    implicit none
    class(brent_class),intent(inout) :: me
    procedure(func)                  :: f
    me%f => f
    end subroutine set_function
Call graph
brent_test calls set_function
integrate_to_event calls set_function
halo_to_rv_diffcorr calls integrate_to_event
rk_test calls integrate_to_event
rk_test_variable_step calls integrate_to_event