solve_lambert_arorarussell – fortran-astrodynamics-toolkit
solve_lambert_arorarussell Subroutine
741 statements
Source File
public subroutine solve_lambert_arorarussell(r1, r2, tofin, mu, lu, nrev, long_way, shortperiod, tolerance, max_iterations, v1, v2)
Solve Lambert's problem using the Arora/Russell method.
Reference
Arora and Russell, "A fast and robust multiple revolution lambert algorithm using a cosine transformation", AAS Hilton Head 2013, AAS 13-728. [see also the journal article]
Lambert_AroraRussell.cpp from EMTG.
!!!!!! test: use ZEROIN for the rootfinder rather than bisection
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ORIGINAL bisection
function for root solve: l(k) = tof(k) - t*
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: r1
real(kind=wp), intent(in), dimension(3) :: r2
real(kind=wp), intent(in) :: tofin
real(kind=wp), intent(in) :: mu
real(kind=wp), intent(in) :: lu
scale factor in km
integer, intent(in) :: nrev
logical, intent(in) :: long_way
logical, intent(in) :: shortperiod
real(kind=wp), intent(in) :: tolerance
integer, intent(in) :: max_iterations
real(kind=wp), intent(out), dimension(3) :: v1
real(kind=wp), intent(out), dimension(3) :: v2
Calls
Called by
Contents
Variables
max_iterations_bisection bisection_error_tolerance sq2 use_zeroin dele_bi0 cos_transfer_angle error k k_n k_m deltak r1mag r2mag tu r1mag_n r2mag_n tof mu_n theta s eps d tau r_buff t_parabolic m_k w_k k_i z alpha f_0 f_1 f_i f_star tof20 tof100 m_i w_ki x_star w t0 t1 sgn_tau var2 var1 dele_biguess var3 sgn_var3 k_biguess m_kbiguess w_kbiguess t_biguess k_bi t_bi m_bi w_bi w_km1 w_kmp5 w_k0 w_kp5 w_k1 tof_km1 tof_kmp5 tof_k0 tof_kp5 tof_k1 m_ki tof_ki w_km1p41 w_km1p38 w_k1dsq2 tof_km1p41 tof_km1p38 tof_k1dsq2 c_1 c_2 c_3 c_4 f_n gamma_1 gamma_2 gamma_3 k_initialguess m dw ddw v vv v3 v4 v5 v6 v7 tofc c sqrtctau dtofc ddtofc low_k high_k middle_k tof_low_k tof_high_k tof_middle_k l_low_k l_high_k l_middle_k f g gdot lu3 luptu r1mag_n_plus_r2mag_n r1mag_n_times_r2mag_n omkt sgn_l_middle_k sgn_l_low_k iterations iterations_bisection iflag r1_n r2_n v1_n v2_n
Functions
l_func acoshar compute_kb compute_tof acosar compute_w safe_acos safe_asin pow
Subroutines
zeroin
Variables
Type Visibility Attributes Name Initial
integer, private, parameter :: max_iterations_bisection = 100
modified from original - better match for izzo and gooding
real(kind=wp), private, parameter :: bisection_error_tolerance = 1e-14_wp
modified from original - better match for izzo and gooding
real(kind=wp), private, parameter :: sq2 = sqrt(two)
logical, private, parameter :: use_zeroin = .false.
jw test
real(kind=wp), private, parameter, dimension(0:19) :: dele_bi0 = [2.848574_wp, 2.969742_wp, 3.019580_wp, 3.046927_wp, 3.064234_wp, 3.076182_wp, 3.084929_wp, 3.091610_wp, 3.096880_wp, 3.101145_wp, 3.104666_wp, 3.107623_wp, 3.110142_wp, 3.112312_wp, 3.114203_wp, 3.115864_wp, 3.117335_wp, 3.118646_wp, 3.119824_wp, 3.120886_wp]
real(kind=wp), private :: cos_transfer_angle
real(kind=wp), private :: error
real(kind=wp), private :: k
real(kind=wp), private :: k_n
real(kind=wp), private :: k_m
real(kind=wp), private :: deltak
real(kind=wp), private :: r1mag
real(kind=wp), private :: r2mag
real(kind=wp), private :: tu
real(kind=wp), private :: r1mag_n
real(kind=wp), private :: r2mag_n
real(kind=wp), private :: tof
real(kind=wp), private :: mu_n
real(kind=wp), private :: theta
real(kind=wp), private :: s
real(kind=wp), private :: eps
real(kind=wp), private :: d
real(kind=wp), private :: tau
real(kind=wp), private :: r_buff
real(kind=wp), private :: t_parabolic
real(kind=wp), private :: m_k
real(kind=wp), private :: w_k
real(kind=wp), private :: k_i
real(kind=wp), private :: z
real(kind=wp), private :: alpha
real(kind=wp), private :: f_0
real(kind=wp), private :: f_1
real(kind=wp), private :: f_i
real(kind=wp), private :: f_star
real(kind=wp), private :: tof20
real(kind=wp), private :: tof100
real(kind=wp), private :: m_i
real(kind=wp), private :: w_ki
real(kind=wp), private :: x_star
real(kind=wp), private :: w
real(kind=wp), private :: t0
real(kind=wp), private :: t1
real(kind=wp), private :: sgn_tau
real(kind=wp), private :: var2
real(kind=wp), private :: var1
real(kind=wp), private :: dele_biguess
real(kind=wp), private :: var3
real(kind=wp), private :: sgn_var3
real(kind=wp), private :: k_biguess
real(kind=wp), private :: m_kbiguess
real(kind=wp), private :: w_kbiguess
real(kind=wp), private :: t_biguess
real(kind=wp), private :: k_bi
real(kind=wp), private :: t_bi
real(kind=wp), private :: m_bi
real(kind=wp), private :: w_bi
real(kind=wp), private :: w_km1
real(kind=wp), private :: w_kmp5
real(kind=wp), private :: w_k0
real(kind=wp), private :: w_kp5
real(kind=wp), private :: w_k1
real(kind=wp), private :: tof_km1
real(kind=wp), private :: tof_kmp5
real(kind=wp), private :: tof_k0
real(kind=wp), private :: tof_kp5
real(kind=wp), private :: tof_k1
real(kind=wp), private :: m_ki
real(kind=wp), private :: tof_ki
real(kind=wp), private :: w_km1p41
real(kind=wp), private :: w_km1p38
real(kind=wp), private :: w_k1dsq2
real(kind=wp), private :: tof_km1p41
real(kind=wp), private :: tof_km1p38
real(kind=wp), private :: tof_k1dsq2
real(kind=wp), private :: c_1
real(kind=wp), private :: c_2
real(kind=wp), private :: c_3
real(kind=wp), private :: c_4
real(kind=wp), private :: f_n
real(kind=wp), private :: gamma_1
real(kind=wp), private :: gamma_2
real(kind=wp), private :: gamma_3
real(kind=wp), private :: k_initialguess
real(kind=wp), private :: m
real(kind=wp), private :: dw
real(kind=wp), private :: ddw
real(kind=wp), private :: v
real(kind=wp), private :: vv
real(kind=wp), private :: v3
real(kind=wp), private :: v4
real(kind=wp), private :: v5
real(kind=wp), private :: v6
real(kind=wp), private :: v7
real(kind=wp), private :: tofc
real(kind=wp), private :: c
real(kind=wp), private :: sqrtctau
real(kind=wp), private :: dtofc
real(kind=wp), private :: ddtofc
real(kind=wp), private :: low_k
real(kind=wp), private :: high_k
real(kind=wp), private :: middle_k
real(kind=wp), private :: tof_low_k
real(kind=wp), private :: tof_high_k
real(kind=wp), private :: tof_middle_k
real(kind=wp), private :: l_low_k
real(kind=wp), private :: l_high_k
real(kind=wp), private :: l_middle_k
real(kind=wp), private :: f
real(kind=wp), private :: g
real(kind=wp), private :: gdot
real(kind=wp), private :: lu3
real(kind=wp), private :: luptu
real(kind=wp), private :: r1mag_n_plus_r2mag_n
real(kind=wp), private :: r1mag_n_times_r2mag_n
real(kind=wp), private :: omkt
integer, private :: sgn_l_middle_k
integer, private :: sgn_l_low_k
integer, private :: iterations
integer, private :: iterations_bisection
integer, private :: iflag
real(kind=wp), private, dimension(3) :: r1_n
real(kind=wp), private, dimension(3) :: r2_n
real(kind=wp), private, dimension(3) :: v1_n
real(kind=wp), private, dimension(3) :: v2_n
Functions
function l_func(k) result(lk)
function for root solve: l(k) = tof(k) - t* interface to the zeroin input function
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: k
Return Value real(kind=wp)
pure elemental function acoshar(b)
fast computation of acosh
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: b
Return Value real(kind=wp)
pure function compute_kb(k_bguess, tau, s, nrev, tolerance, max_iterations, sq2, eps) result(k)
newton's method to find k_bi given tau, s, nrev, and initial guess for k_bi
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: k_bguess
real(kind=wp), intent(in) :: tau
real(kind=wp), intent(in) :: s
integer, intent(in) :: nrev
real(kind=wp), intent(in) :: tolerance
integer, intent(in) :: max_iterations
real(kind=wp), intent(in) :: sq2
real(kind=wp), intent(in) :: eps
Return Value real(kind=wp)
pure function compute_tof(k, s, tau, w) result(tofc)
calculate tof function for a given k, tau,
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: k
real(kind=wp), intent(in) :: s
real(kind=wp), intent(in) :: tau
real(kind=wp), intent(in) :: w
Return Value real(kind=wp)
pure elemental function acosar(x)
fast, rough computation of acos()
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x
Return Value real(kind=wp)
pure function compute_w(k, m, nrev) result(w)
function to compute the parameter w
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: k
real(kind=wp), intent(in) :: m
integer, intent(in) :: nrev
Return Value real(kind=wp)
pure elemental function safe_acos(x)
return x > one ? zero : (x < -one ? pi : acos(x))
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x
Return Value real(kind=wp)
pure elemental function safe_asin(x)
safe_asin = x > one ? -piover2 : (x < -one ? piover2 : asin(x))
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x
Return Value real(kind=wp)
pure elemental function pow(x, y)
return x**y
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: x
real(kind=wp), intent(in) :: y
Return Value real(kind=wp)
Subroutines
subroutine zeroin(f, ax, bx, fax, fbx, tol, xzero, fzero, iflag)
Find a zero of the function in the given interval to within a tolerance , where is the relative machine precision defined as the smallest representable number such that .
It is assumed that and have opposite signs.
References
R. P. Brent, "An algorithm with guaranteed convergence for finding a zero of a function", The Computer Journal, Vol 14, No. 4., 1971.
R. P. Brent, "Algorithms for minimization without derivatives", Prentice-Hall, Inc., 1973.
See also
zeroin.f from Netlib
Arguments
Type Intent Optional Attributes Name
procedure(func) :: f
the function to find the root of
real(kind=wp), intent(in) :: ax
left endpoint of initial interval
real(kind=wp), intent(in) :: bx
right endpoint of initial interval
real(kind=wp), intent(in) :: fax
f(ax) for endpoint
real(kind=wp), intent(in) :: fbx
f(ax) for endpoint
real(kind=wp), intent(in) :: tol
desired length of the interval of uncertainty of the final result (>=0)
real(kind=wp), intent(out) :: xzero
abscissa approximating a zero of f in the interval ax,bx
real(kind=wp), intent(out) :: fzero
value of f at the root (f(xzero))
integer, intent(out) :: iflag
status flag (-1=error, 0=root found)
Call graph
solve_lambert_arorarussell calls pow, compute_kb, compute_tof, compute_w, zeroin, safe_acos
lambert_test calls solve_lambert_arorarussell