ucross – fortran-astrodynamics-toolkit
ucross Function
Jacob Williams
7 statements
Source File
public pure function ucross(v1, v2) result(u)
Unit vector of the cross product of two 3x1 vectors
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(3) :: v1
real(kind=wp), intent(in), dimension(3) :: v2
Return Value real(kind=wp),dimension(3)
Calls
Called by
Contents
Source Code
ucross
Source Code
    pure function ucross(v1,v2) result(u)
    implicit none
    real(wp),dimension(3),intent(in) :: v1
    real(wp),dimension(3),intent(in) :: v2
    real(wp),dimension(3)            :: u
    u = unit(cross(v1,v2))
    end function ucross
Call graph
ucross calls unit, cross
solve_lambert_izzo calls ucross
bplane calls ucross
lambert_test calls solve_lambert_izzo
bplane_test calls bplane