unit – fortran-astrodynamics-toolkit
unit Function
Jacob Williams
12 statements
Source File
public pure function unit(r) result(u)
Unit vector
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:) :: r
Return Value real(kind=wp), dimension(size(r))
Called by
Source Code
    pure function unit(r) result(u)
    implicit none
    real(wp),dimension(:),intent(in) :: r
    real(wp),dimension(size(r))      :: u
    real(wp) :: rmag
    rmag = norm2(r)
    if (rmag==zero) then
        u = zero
    else
        u = r / rmag
    end if
    end function unit
Call graph
apparent_position calls unit, axis_angle_rotation
axis_angle_rotation calls unit
axis_angle_rotation_to_rotation_matrix calls unit
bplane calls unit, ucross
calculate_bplane_data calls unit
cartesian_to_equinoctial calls unit
cubic_shadow_model calls unit
from_ijk_to_lvlh_mat calls unit
from_ijk_to_rsw_mat calls unit
from_ijk_to_vuw_mat calls unit
get_c_cdot_two_body_rotating calls unit
solar_fraction calls unit
solar_fraction_alt calls unit
solar_fraction_alt2 calls unit
solve_lambert_gooding calls unit
solve_lambert_izzo calls unit, ucross
ucross calls unit
from_ijk_to_lvlh calls from_ijk_to_lvlh_mat
from_ijk_to_rsw calls from_ijk_to_rsw_mat
from_ijk_to_vuw calls from_ijk_to_vuw_mat
bplane_test calls bplane, calculate_bplane_data
get_c_cdot_two_body_rotating_pulsating calls get_c_cdot_two_body_rotating
get_sun_fraction calls apparent_position, cubic_shadow_model, solar_fraction, solar_fraction_alt, solar_fraction_alt2
lambert_test calls solve_lambert_gooding, solve_lambert_izzo
lighting_module_test calls solar_fraction, solar_fraction_alt, solar_fraction_alt2
modified_equinoctial_test calls cartesian_to_equinoctial
vector_test calls axis_angle_rotation, axis_angle_rotation_to_rotation_matrix
from_lvlh_to_ijk_mat calls from_ijk_to_lvlh
from_rsw_to_ijk_mat calls from_ijk_to_rsw
from_vuw_to_ijk_mat calls from_ijk_to_vuw
relative_motion_test calls from_ijk_to_lvlh, from_ijk_to_rsw
from_lvlh_to_ijk calls from_lvlh_to_ijk_mat
from_rsw_to_ijk calls from_rsw_to_ijk_mat
from_vuw_to_ijk calls from_vuw_to_ijk_mat