wrap_angle – fortran-astrodynamics-toolkit
wrap_angle Function
7 statements
Source File
public pure elemental function wrap_angle(a) result(r)
Wrap an angle (in rad) from -pi to pi.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: a
Return Value real(kind=wp)
Called by
Source Code
    pure elemental function wrap_angle(a) result(r)
    implicit none
    real(wp),intent(in) :: a
    real(wp)            :: r
    r = mod(a,twopi)
    if (abs(r)>pi) r = r - sign(twopi,r)
    end function wrap_angle
Call graph
cubic_shadow_model calls wrap_angle
halo_to_rv_diffcorr calls wrap_angle
rv_to_orbital_elements calls wrap_angle
get_sun_fraction calls cubic_shadow_model