xyz2philambda – fortran-astrodynamics-toolkit
xyz2philambda Subroutine
50 statements
Source File
private subroutine xyz2philambda(ax, ay, b, x, y, z, phi, lambda)
Determination of the geodetic latitude and longitude
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: ax
real(kind=wp), intent(in) :: ay
real(kind=wp), intent(in) :: b
real(kind=wp), intent(in) :: x
real(kind=wp), intent(in) :: y
real(kind=wp), intent(in) :: z
real(kind=wp), intent(out) :: phi
real(kind=wp), intent(out) :: lambda
Calls
Called by
Contents
Source Code
xyz2philambda
Source Code
    subroutine xyz2philambda(ax, ay, b, x, y, z, phi, lambda)
     real(wp),intent(in) :: ax, ay, b, x, y, z
     real(wp),intent(out) :: phi, lambda
     real(wp) :: ee2,ex2,s0,SS0,Sphi,Cphi,Slambda,Clambda,&
                 Den,P,L,D,NN,onemee2,onemex2
     integer :: n
     real(wp),dimension(3,2) :: J
     real(wp),dimension(3,1) :: dl,UU
     real(wp),dimension(2,2) :: Nmat
     real(wp),dimension(2,1) :: u, dx
     real(wp),dimension(1,1) :: tmp
     real(wp),dimension(2,2) :: NmatTmp
     real(wp),dimension(3) :: r
     ee2 = (ax*ax - ay*ay)/(ax*ax)
     ex2 = (ax*ax - b*b)/(ax*ax)
     onemee2 = one - ee2
     onemex2 = one - ex2
     call xyz2fl(ax, ay, b, x, y, z, phi, lambda) ! use analytical one for initial guess
    ! JW: is there some bug below? ..........  I don't think it is working right.
     s0 = zero
     do n = 1, 100
         SS0 = s0
         ! Design Matrix J
         Sphi = sin(phi)
         Cphi = cos(phi)
         Slambda = sin(lambda)
         Clambda = cos(lambda)
         NN  = ax/sqrt(1.0_wp-ex2*Sphi*Sphi-ee2*Cphi*Cphi*Slambda*Slambda)
         Den = two*(1.0_wp-ex2*Sphi*Sphi-ee2*Cphi*Cphi*Slambda*Slambda)**(3.0_wp/two)
         P   = -ax*(ex2-ee2*Slambda*Slambda)*sin(two*phi)/Den
         L   = -ax*ee2*Cphi*Cphi*sin(2*lambda)/Den
         J(1,1) = (P*Cphi-NN*Sphi)*Clambda
         J(2,1) = onemee2*(P*Cphi-NN*Sphi)*Slambda
         J(3,1) = onemex2*(P*Sphi+NN*Cphi)
         J(1,2) = (L*Clambda-NN*Slambda)*Cphi
         J(2,2) = onemee2*(L*Slambda+NN*Clambda)*Cphi
         J(3,2) = onemex2*L*Sphi
         ! Vector dl
         call geodetic_to_cartesian_triaxial_2(ax, ay, b, phi, lambda, 0.0_wp, r) ! just use the main one with alt=0
         dl(:,1) = [x,y,z] - r
         ! write(*,*) 'phi     =', phi
         ! write(*,*) 'lambda  =', lambda
         ! Solution
         Nmat    = matmul(transpose(J),J)
         u       = matmul(transpose(J),dl)
         D       = Nmat(1,1)*Nmat(2,2) - Nmat(1,2)*Nmat(2,1)
         NmatTmp = transpose(reshape([Nmat(2,2), -Nmat(1,2), -Nmat(2,1), Nmat(1,1)], [2,2]))
         dx      = matmul((NmatTmp / D) , u)
        ! write(*,*) 'correction: ', n, dx
         phi     = phi    + dx(1,1)   ! corrections
         lambda  = lambda + dx(2,1)
         UU      = matmul(J,dx) - dl
         tmp     = sqrt(matmul(transpose(UU),UU))
         s0      = tmp(1,1)
         if (s0 == SS0) exit     ! JW : this is not really a good stop criterion....
                                 !      dx bounces around very small values....
         !write(*,*) 'abs(s0 - SS0): ', abs(s0 - SS0)
         if (all(abs(dx) <= 10*epsilon(1.0_wp))) exit ! JW: how about this ??
                                                      ! just check the correction ??
     end do
    end subroutine xyz2philambda
Call graph
xyz2philambda calls xyz2fl, geodetic_to_cartesian_triaxial_2
cartesian_to_geodetic_triaxial calls xyz2philambda