extract_vector – fortran-astrodynamics-toolkit
extract_vector Interface
3 statements
Source File
public interface extract_vector
Calls
Called by
Contents
Module Procedures
extract_vector_from_vector extract_scalar_from_vector
Module Procedures
private subroutine extract_vector_from_vector(vals, x, i)
Extract a vector from the vector and update the index
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out), dimension(:) :: vals
real(kind=wp), intent(in), dimension(:) :: x
integer, intent(inout) :: i
should be initialized to 0 before the first call
private subroutine extract_scalar_from_vector(val, x, i)
Extract the value from the vector and update the index
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out) :: val
real(kind=wp), intent(in), dimension(:) :: x
integer, intent(inout) :: i
should be initialized to 0 before the first call
Call graph
extract_vector calls extract_vector_from_vector, extract_scalar_from_vector
extract_vector_from_vector calls extract_vector