fill_vector – fortran-astrodynamics-toolkit
fill_vector Interface
3 statements
Source File
public interface fill_vector
Calls
Called by
Contents
Module Procedures
fill_vector_with_vector fill_vector_with_scalar fill_char_vector_with_vector fill_char_vector_with_scalar
Module Procedures
private subroutine fill_vector_with_vector(x, vals, i)
Put the vector in the vector and update the index
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(inout), dimension(:) :: x
real(kind=wp), intent(in), dimension(:) :: vals
integer, intent(inout) :: i
should be initialized to 0 before the first call
private subroutine fill_vector_with_scalar(x, val, i)
Put the value in the vector and update the index
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(inout), dimension(:) :: x
real(kind=wp), intent(in) :: val
integer, intent(inout) :: i
should be initialized to 0 before the first call
private subroutine fill_char_vector_with_vector(x, vals, i)
Put the vector in the vector and update the index (character version)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout), dimension(:) :: x
character(len=*), intent(in), dimension(:) :: vals
integer, intent(inout) :: i
should be initialized to 0 before the first call
private subroutine fill_char_vector_with_scalar(x, val, i)
Put the value in the vector and update the index (character version)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(inout), dimension(:) :: x
character(len=*), intent(in) :: val
integer, intent(inout) :: i
should be initialized to 0 before the first call
Call graph
fill_vector calls fill_vector_with_vector, fill_char_vector_with_scalar, fill_vector_with_scalar, fill_char_vector_with_vector
fill_vector_with_vector calls fill_vector
fill_char_vector_with_vector calls fill_vector