from_ijk_to_lvlh – fortran-astrodynamics-toolkit
from_ijk_to_lvlh Interface
4 statements
Source File
public interface from_ijk_to_lvlh
Conversion from IJK to LVLH
Calls
Called by
Module Procedures
private subroutine from_ijk_to_lvlh_mat(mu, r, v, a, c, cdot)
Author
Jacob Williams
Date
4/19/2014
Compute the transformation matrices to convert IJK to LVLH.
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: mu
gravitational parameter [km^3/s^2]
real(kind=wp), intent(in), dimension(3) :: r
position vector of target [km]
real(kind=wp), intent(in), dimension(3) :: v
velocity vector of target [km/s]
real(kind=wp), intent(in), optional, dimension(3) :: a
acceleration vector of target [km/s^2] (if not present, then a torque-free force model is assumed)
real(kind=wp), intent(out), dimension(3,3) :: c
C transformation matrix
real(kind=wp), intent(out), optional, dimension(3,3) :: cdot
CDOT transformation matrix
private subroutine from_ijk_to_lvlh_rv(mu, rt_ijk, vt_ijk, r_ijk, v_ijk, dr_lvlh, dv_lvlh)
Author
Jacob Williams
Date
8/23/2014
Transform a position (and optionally velocity) vector from IJK to LVLH.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: mu
gravitational parameter [km^3/s^2]
real(kind=wp), intent(in), dimension(3) :: rt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: vt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: r_ijk
Chaser IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: v_ijk
Chaser IJK absolute position vector [km]
real(kind=wp), intent(out), dimension(3) :: dr_lvlh
Chaser LVLH position vector relative to target [km]
real(kind=wp), intent(out), optional, dimension(3) :: dv_lvlh
Chaser LVLH position vector relative to target [km]
Call graph
from_ijk_to_lvlh calls from_ijk_to_lvlh_mat, from_ijk_to_lvlh_rv
from_ijk_to_lvlh_mat calls cross, uhat_dot, unit
from_ijk_to_lvlh_rv calls from_ijk_to_frame_rv
from_lvlh_to_ijk_mat calls from_ijk_to_lvlh
relative_motion_test calls from_ijk_to_lvlh
from_lvlh_to_ijk calls from_lvlh_to_ijk_mat