from_vuw_to_ijk – fortran-astrodynamics-toolkit
from_vuw_to_ijk Interface
4 statements
Source File
public interface from_vuw_to_ijk
Conversion from vuw to IJK
Calls
Module Procedures
private subroutine from_vuw_to_ijk_mat(mu, r, v, a, c, cdot)
Compute the transformation matrices to convert VUW to IJK.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: mu
gravitational parameter [km^3/s^2]
real(kind=wp), intent(in), dimension(3) :: r
position vector of target [km]
real(kind=wp), intent(in), dimension(3) :: v
velocity vector of target [km/s]
real(kind=wp), intent(in), optional, dimension(3) :: a
acceleration vector of target [km/s^2] (if not present, then a torque-free force model is assumed)
real(kind=wp), intent(out), dimension(3,3) :: c
C transformation matrix
real(kind=wp), intent(out), optional, dimension(3,3) :: cdot
CDOT transformation matrix
private subroutine from_vuw_to_ijk_rv(mu, rt_ijk, vt_ijk, dr_vuw, dv_vuw, r_ijk, v_ijk)
Transform a position (and optionally velocity) vector from VUW to IJK.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: mu
gravitational parameter [km^3/s^2]
real(kind=wp), intent(in), dimension(3) :: rt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: vt_ijk
Target IJK absolute position vector [km]
real(kind=wp), intent(in), dimension(3) :: dr_vuw
Chaser vuw position vector relative to target [km]
real(kind=wp), intent(in), dimension(3) :: dv_vuw
Chaser vuw position vector relative to target [km]
real(kind=wp), intent(out), dimension(3) :: r_ijk
Chaser IJK absolute position vector [km]
real(kind=wp), intent(out), optional, dimension(3) :: v_ijk
Chaser IJK absolute position vector [km]
Call graph
from_vuw_to_ijk calls from_vuw_to_ijk_mat, from_vuw_to_ijk_rv
from_vuw_to_ijk_mat calls from_ijk_to_vuw
from_vuw_to_ijk_rv calls from_frame_to_ijk_rv
from_ijk_to_vuw calls from_ijk_to_vuw_mat, from_ijk_to_vuw_rv
from_ijk_to_vuw_mat calls cross, uhat_dot, unit
from_ijk_to_vuw_rv calls from_ijk_to_frame_rv