julian_date – fortran-astrodynamics-toolkit
julian_date Interface
3 statements
Source File
public interface julian_date
calendar date to julian date
Calls
Called by
Contents
Module Procedures
julian_date_realsec julian_date_intsec
Module Procedures
private pure function julian_date_realsec(y, m, d, hour, minute, second) result(julian_date)
Author
Jacob Williams
Date
1/21/2015
Returns the Julian date for the specified YEAR, MONTH, DAY, HR, MIN, SEC.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: y
integer, intent(in) :: m
integer, intent(in) :: d
integer, intent(in) :: hour
integer, intent(in) :: minute
real(kind=wp), intent(in) :: second
Return Value real(kind=wp)
private pure function julian_date_intsec(y, m, d, hour, minute, second) result(julian_date)
Author
Jacob Williams
Date
1/21/2015
Returns the Julian date for the specified YEAR, MONTH, DAY, HR, MIN, SEC.
Read more…
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: y
integer, intent(in) :: m
integer, intent(in) :: d
integer, intent(in) :: hour
integer, intent(in) :: minute
integer, intent(in) :: second
Return Value real(kind=wp)
Call graph
julian_date calls julian_date_intsec, julian_date_realsec
julian_date_intsec calls julian_date_realsec
julian_date_realsec calls julian_day
time_module_test calls julian_date